name: Swift

on:
  [ push ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: kobiton
      run: npm install

    - name: npm star
      run: npm start

    - name: kobiton2
      run: node xcuitest.js
