name: Swift

on:
  [ push ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: npm install
      run: npm start
    - name: kobiton
      run: npm install
    - name: kobiton2
      run: node xcuitest.js
